name: Java CI with Gradle

on:
  push:
    branches:
      - main # 'main' салбарт хийх push үйлдэлд энэ workflow ажиллана.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests
      run: ./gradlew test

    - name: Push changes
      run: |
        git config --global user.name "Your Name"
        git config --global user.email "your-email@example.com"
        git add .
        git commit -m "Automated push"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
